# .github/workflows/job_manager.yml
name: Daily Job Manager

on:
  schedule:
    # Runs every day at 17:00 UTC (1:00 AM SGT the next day)
    - cron: "0 17 * * *"
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  manage:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # Checks out your code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure requirements.txt includes httpx if not already added
          pip install -r requirements.txt

      - name: Run job manager script
        env:
          # Define environment variables needed by your script
          # These should be set as Secrets in your GitHub repository settings
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          # Add other secrets if job_manager.py needs them (e.g., proxies if used differently)
        run: python job_manager.py # Execute the job manager script