name: Parse Resume Manually

on:
  workflow_dispatch: 

jobs:
  parse_resume_job:
    runs-on: ubuntu-latest 

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found. Please create one with necessary packages."
            # Optionally, install known dependencies directly if requirements.txt is missing
            # pip install pdfplumber google-generativeai supabase
            exit 1
          fi

      - name: Run resume parser script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GEMINI_FIRST_API_KEY: ${{ secrets.GEMINI_FIRST_API_KEY }} # Gemini API Key
        run: python resume_parser.py
